// Where: wikibrowser/lib/wiki-worker-markdown.ts
// What: Markdown rendering and path slug handling for generated wiki drafts.
// Why: LLM output must be converted into a stable review page shape before VFS writes.
import type { SearchNodeHit, WikiNode } from "@/lib/types";
import { SCHEMA_VERSION, type WikiDraft, type WikiDraftItem } from "@/lib/wiki-worker-types";

export function slugForDraft(draft: WikiDraft): string {
  const slug = slugify(draft.slug) || slugify(draft.title);
  if (!slug) {
    throw new Error("generated draft needs a usable title or slug");
  }
  return slug;
}

export function renderDraftMarkdown(draft: WikiDraft, source: WikiNode, contextHits: SearchNodeHit[]): string {
  return [
    `# ${draft.title}`,
    "",
    "## Status",
    "",
    "- State: Draft",
    `- Source: [${source.path}](${source.path})`,
    `- Generated by: wiki-worker v${SCHEMA_VERSION}`,
    "",
    "## Summary",
    "",
    draft.summary,
    "",
    renderItems("Key Facts", draft.key_facts),
    renderItems("Decisions", draft.decisions),
    renderItems("Open Questions", draft.open_questions),
    renderItems("Follow-ups", draft.follow_ups),
    renderContext(contextHits),
    "## Provenance",
    "",
    `- source_path: ${source.path}`,
    `- source_etag: ${source.etag}`
  ]
    .filter((part) => part !== "")
    .join("\n");
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function renderItems(title: string, items: WikiDraftItem[]): string {
  if (items.length === 0) {
    return `## ${title}\n\n- none\n`;
  }
  return `## ${title}\n\n${items.map((item) => `- ${item.text} ([source](${item.source_path}))`).join("\n")}\n`;
}

function renderContext(contextHits: SearchNodeHit[]): string {
  if (contextHits.length === 0) return "";
  return `## Related Context\n\n${contextHits.map((hit) => `- [${hit.path}](${hit.path})`).join("\n")}\n`;
}
